version: "2"
services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
    environment:
      - POSTGRES_HOST=postgres
    command: sh ./setup.sh
    command: gunicorn FizzBuzz.wsgi:application -b :8000
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=fizzbuzzpassword
      - POSTGRES_USER=fizzbuzzuser
      - POSTGRES_DB=fizzbuzz