version: "2"
services:
  fizzbuzz:
    build: ./app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
    command: sh ./setup.sh

  postgres:
    image: "postgres:9.6"
    environment:
      - POSTGRES_PASSWORD=fizzbuzzpassword
      - POSTGRES_USER=fizzbuzzuser
      - POSTGRES_DB=fizzbuzz