version: "3.6"
services:
  fizzbuzz:
    build: ./app
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
    command: sh ./setup.sh
    volumes:
      - ./app/FizzBuzz/:/app/FizzBuzz/
    networks:
      - fizzbuzznet
  postgres:
    image: "postgres:11.4"
    environment:
      - POSTGRES_PASSWORD=fizzbuzzpassword
      - POSTGRES_USER=fizzbuzzuser
      - POSTGRES_DB=fizzbuzz
    networks:
      - fizzbuzznet
networks:
  fizzbuzznet:
